name: Run JUnit5 tests

on: [push, pull_request]
jobs:
  gradle:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports:
          - 5432/tcp
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: 14
      - uses: eskatos/gradle-command-action@v1
        with:
          gradle-version: 6.3
          arguments: initAll buildGulp build --no-daemon
        env:
          POSTGRES_DB: postgres
          POSTGRES_PORT: ${{ job.services.postgres.port[5432] }}
